import type { Metadata } from "next";
import { Lato, Outfit } from "next/font/google";
import "./globals.css";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
})

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfitSans.variable} ${lato.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
